import type { SkillMetric } from '../models/types'

export const metrics: SkillMetric[] = [
  {
    id: 'python',
    label: 'Python',
    category: 'backend',
    level: 85,
    trend: 'up',
    isPrimary: true,
  },
  {
    id: 'fast-api',
    label: 'FastAPI',
    category: 'backend',
    level: 75,
    trend: 'up',
    isPrimary: true,
  },
  {
    id: 'flask',
    label: 'Flask',
    category: 'backend',
    level: 85,
    trend: 'steady',
    isPrimary: true,
  },
  {
    id: 'postgresql',
    label: 'PostgreSQL',
    category: 'backend',
    level: 90,
    trend: 'up',
    isPrimary: true,
  },
  {
    id: 'docker-k8s',
    label: 'Docker & Kubernetes',
    category: 'devops',
    level: 70,
    trend: 'up',
    isPrimary: true,
  },
  {
    id: 'prom-graf',
    label: 'Prometheus & Grafana',
    category: 'backend',
    level: 50,
    trend: 'up',
    isPrimary: true,
  },
  {
    id: 'sentry',
    label: 'Sentry',
    category: 'backend',
    level: 50,
    trend: 'up',
    isPrimary: true,
  },
  {
    id: 'redis',
    label: 'Redis',
    category: 'backend',
    level: 70,
    trend: 'up',
    isPrimary: true,
  },
  {
    id: 'react',
    label: 'React',
    category: 'frontend',
    level: 65,
    trend: 'steady',
    isPrimary: false,
  },
  {
    id: 'html-css',
    label: 'HTML & CSS',
    category: 'frontend',
    level: 65,
    trend: 'steady',
    isPrimary: false,
  },
  {
    id: 'node-js',
    label: 'Node.js / TypeScript',
    category: 'backend',
    level: 60,
    trend: 'down',
    isPrimary: false,
  },
  {
    id: 'elixir',
    label: 'Elixir / Phoenix',
    category: 'backend',
    level: 40,
    trend: 'down',
    isPrimary: false,
  },
  {
    id: 'java',
    label: 'Java',
    category: 'backend',
    level: 25,
    trend: 'steady',
    isPrimary: false,
  },
]
