import type { SkillMetric } from '../models/types'

export const metrics: SkillMetric[] = [
  {
    id: 'python',
    label: 'Python (4 years)',
    category: 'backend',
    level: 85,
    trend: 'up',
    isPrimary: true,
  },
  {
    id: 'fast-api',
    label: 'FastAPI (1 year)',
    category: 'backend',
    level: 75,
    trend: 'up',
    isPrimary: true,
  },
  {
  id: 'flask',
    label: 'Flask (3 years)',
    category: 'backend',
    level: 85,
    trend: 'steady',
    isPrimary: true,
  },
  {
    id: 'postgresql',
    label: 'PostgreSQL (6 years)',
    category: 'backend',
    level: 90,
    trend: 'up',
    isPrimary: true,
  },
  {
    id: 'docker-k8s',
    label: 'Docker & Kubernetes (5 years)',
    category: 'devops',
    level: 70,
    trend: 'up',
    isPrimary: true,
  },
  {
    id: 'prom-graf',
    label: 'Prometheus & Grafana (1 year)',
    category: 'backend',
    level: 50,
    trend: 'up',
    isPrimary: true,
  },
  {
    id: 'sentry',
    label: 'Sentry (3 years)',
    category: 'backend',
    level: 50,
    trend: 'up',
    isPrimary: true,
  },
  {
    id: 'redis',
    label: 'Redis (4 years)',
    category: 'backend',
    level: 70,
    trend: 'up',
    isPrimary: true,
  },
  {
    id: 'react',
    label: 'React (1 year)',
    category: 'frontend',
    level: 65,
    trend: 'steady',
    isPrimary: false,
  },
  {
    id: 'node-js',
    label: 'Node.js / TypeScript (1 year)',
    category: 'backend',
    level: 60,
    trend: 'down',
    isPrimary: false,
  },
  {
    id: 'elixir',
    label: 'Elixir / Phoenix (2 years)',
    category: 'backend',
    level: 40,
    trend: 'down',
    isPrimary: false,
  },
  {
    id: 'java',
    label: 'Java (6 months)',
    category: 'backend',
    level: 25,
    trend: 'steady',
    isPrimary: false,
  },
]
